### ISSUE TITLE
git gone -fv prune fails with error code

### ISSUE THREAD

**Issue by RLHSI** [lunaryorn/git-gone#5]
Running `git gone -fv prune` fails with the following error message:

```
Error: Error { code: -1, klass: 12, message: "request failed with status code: 401" }
```

Running `git fetch --all --prune` and then `git gone prune` works as expected.

Environment:

* Windows 10 x64 1809
* rustc 1.36.0 (a53f9df32 2019-07-03)
* git-gone 0.1.2

**Comment by lunaryorn** [comment]
I presume you fetch from a HTTP remote which requires authentication? Looks as if libgit2 doesn't use the same authentication mechanism as the original git and fails to use the latter's credentials for your remote.

I don't think I can fix this though; I don't really know libgit and I don't have any repo to test this one (all private repos I use require SSH).

**Comment by lunaryorn** [comment]
Took a quick look at the documentation; I guess you need to add a credentials callback to the fetch operation and call out to `CredentialHelper` to obtain credentials from Git, or otherwise prompt for username/password.

I'd happy to merge a pull request and I can help you with the Rust part, but I don't really want to fix this issue myself; I don't really have much time for this, and as said, I don't use HTTP for private remotes.

**Comment by RLHSI** [comment]
Yes I'm using an internal git endpoint that uses authentication, that's most likely what the error is.

No worries! I was just reporting the issue. Because `git gone prune` works as expected, this isn't really a big deal :)  I've never programmed in Rust before so this might be over my head, but I might try it when I have some free time in the coming weeks.
